#!/usr/bin/env python3
"""Surviving owner for one candidate snapshot/worktree and capacity lease.

The verifier supplies only paths it created below its fresh temporary parent
and exact process-session leaders it spawned. This process outlives a killed
verifier, reaps only those registered groups, then removes the exact
registered worktree and parent.
"""
from __future__ import annotations

import argparse
import os
import shutil
import signal
import subprocess
import sys
import threading
import time
from pathlib import Path

import psutil

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from scripts.test_capacity import CapacityManager


_START_TIME_TOLERANCE = 1e-6


def _read_process_groups(fd: int, groups: dict[int, float], done: threading.Event) -> None:
    """Read trusted parent-side group registrations until its fd closes."""
    buffered = b""
    try:
        while True:
            chunk = os.read(fd, 4096)
            if not chunk:
                break
            buffered += chunk
            lines = buffered.split(b"\n")
            buffered = lines.pop()
            for line in lines:
                try:
                    pid, started = line.decode("ascii").split(" ", 1)
                    groups[int(pid)] = float(started)
                except (UnicodeDecodeError, ValueError):
                    # The fd is never exposed to candidate code. A malformed
                    # record means a parent bug; it cannot authorize a kill.
                    continue
    finally:
        try:
            os.close(fd)
        except OSError:
            pass
        done.set()


def _same_process(pid: int, started: float) -> bool:
    try:
        return abs(psutil.Process(pid).create_time() - started) <= _START_TIME_TOLERANCE
    except psutil.Error:
        return False


def _group_members(pid: int, started: float) -> list[int]:
    """Return members of one registered session group, never inferred by cwd."""
    # A reused leader PID invalidates this registration completely: do not
    # inspect or signal an arbitrary new process group with the same number.
    if psutil.pid_exists(pid) and not _same_process(pid, started):
        return []
    members: list[int] = []
    for proc in psutil.process_iter(["pid", "status"]):
        candidate = proc.info["pid"]
        try:
            # A zombie has already exited. Waiting for PID disappearance would
            # retain capacity until its unrelated reaper happens to run, even
            # though there is no descendant left to schedule alongside.
            if proc.info["status"] == psutil.STATUS_ZOMBIE:
                continue
            if os.getpgid(candidate) == pid:
                members.append(candidate)
        except (OSError, psutil.Error):
            pass
    return members


def _reap_registered_groups(groups: dict[int, float]) -> None:
    for pid, started in groups.items():
        members = _group_members(pid, started)
        if not members:
            continue
        try:
            os.killpg(pid, signal.SIGKILL)
        except OSError:
            # If a leader already exited, process-group signalling can fail;
            # the members are still identity-authorized by the registration.
            for member in members:
                try:
                    os.kill(member, signal.SIGKILL)
                except ProcessLookupError:
                    pass


def _registered_groups_gone(groups: dict[int, float]) -> bool:
    return not any(_group_members(pid, started) for pid, started in groups.items())


def _cleanup(repository: Path, worktree: Path | None, parent: Path, groups: dict[int, float]) -> None:
    # The parent is generated by tempfile and worktree, if present, is its
    # fixed child. Refuse broad/unrelated targets even if invoked wrongly.
    valid_parent = parent.name.startswith(("lifeos-pushed-candidate-", "lifeos-local-candidate-"))
    if not valid_parent or (worktree is not None and worktree.parent != parent):
        return
    _reap_registered_groups(groups)
    # Capacity must remain held until every exact registered group is gone.
    # A timeout here would make a still-live descendant invisible to the
    # scheduler and reintroduce the leak this owner exists to prevent.
    while not _registered_groups_gone(groups):
        _reap_registered_groups(groups)
        time.sleep(0.05)
    if worktree is not None:
        subprocess.run(["git", "-C", str(repository), "worktree", "remove", "--force", str(worktree)], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    shutil.rmtree(parent, ignore_errors=True)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--owner-fd", type=int, required=True)
    parser.add_argument("--ready-fd", type=int, required=True)
    parser.add_argument("--process-fd", type=int, required=True)
    parser.add_argument("--repository", type=Path, required=True)
    parser.add_argument("--worktree", type=Path)
    parser.add_argument("--parent", type=Path, required=True)
    parser.add_argument("--workers", type=int, required=True)
    parser.add_argument("--capacity-root", type=Path, required=True)
    parser.add_argument("--capacity-total", type=int, required=True)
    parser.add_argument("--capacity-max-run", type=int, required=True)
    args = parser.parse_args(argv)
    lease = None
    groups: dict[int, float] = {}
    registry_done = threading.Event()
    registry_reader = threading.Thread(
        target=_read_process_groups, args=(args.process_fd, groups, registry_done), daemon=True,
    )
    registry_reader.start()
    try:
        manager = CapacityManager(
            args.capacity_total, max_run_workers=args.capacity_max_run,
            _state_root=args.capacity_root,
        )
        lease = manager.acquire(args.workers)
        os.write(args.ready_fd, b"1")
        os.close(args.ready_fd)
        os.read(args.owner_fd, 1)  # EOF on normal exit or SIGKILL of verifier
    finally:
        for fd in (args.owner_fd, args.ready_fd):
            try:
                os.close(fd)
            except OSError:
                pass
        # The verifier owns the only registry write fd and candidate commands
        # never inherit it, so EOF is the synchronization point. Do not race
        # cleanup against a mutable partially-read registration dictionary.
        registry_done.wait()
        worktree = args.worktree.resolve() if args.worktree is not None else None
        _cleanup(args.repository.resolve(), worktree, args.parent.resolve(), groups)
        if lease is not None:
            lease.release()
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
