"""
Vault write API — lets MCP-only clients (cloud agents) put files into the vault.

Read access is already covered by `lifeos_search`, `lifeos_ask`, etc. There was
no write path, which made tasks like "produce X.md in the vault" unsolvable for
the cloud agent (its tool surface is read-only RAG queries). This endpoint
closes that gap; the MCP server picks it up automatically as `lifeos_vault_write`
via the OpenAPI→curated-endpoint bridge.

Path validation: requested paths must be relative, must not contain `..`, and
must resolve under `settings.vault_path` after `Path.resolve()`. Parent dirs
are created on demand so a single call can write into a new subtree.

`Personal/Journal/` is additionally reserved end-to-end for every caller of
this endpoint (#659) *when the journal persona is enabled on this install*
(#769): those files are generated by `gsheet_sync.py` from a Google Sheet and
carry `row_hash`/`synced_at` plus the scalars (`mood`/`stress`/`sleep`/
`one_word`) that `api/routes/journal_trends.py` analyzes. A free-form write
there would be silently clobbered by the next sync and would corrupt those
analytics, so it is blocked here rather than left to caller discipline (e.g.
a persona's prompt instructions). Free-form fragment capture belongs in
`Personal/Log/` instead — see `config/personas/journal.md`.

The reservation only makes sense where the generated file it protects can
exist, so it is gated on whether either of the two independent config
surfaces that produce it is actually configured on this install (#769): the
same "is the journal persona configured" signal
`api/routes/journal_ingest.py` already uses (a `journal` entry in
`settings.telegram_bots`, i.e. `TELEGRAM_JOURNAL_BOT_TOKEN` is set), OR
`gsheet_sync.py`'s own `journal_notes` output being enabled in
`config/gsheet_sync.yaml` — an install can have either configured without
the other, and both independently generate real files under
`Personal/Journal/` that this reservation exists to protect. A fresh clone
with neither pipeline configured is not blocked from writing there. An
install that already has either configured (the maintainer's has both) sees
no change.
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Literal

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

from api.services.gsheet_sync import journal_notes_configured
from config.settings import settings

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/vault", tags=["vault"])

# Reserved subtree — see the module docstring. Matched as an exact leading
# path-parts prefix so `Personal/Journal-adjacent.md` (a sibling file, not a
# child of the reserved dir) is unaffected.
_RESERVED_PREFIX = ("Personal", "Journal")

# The journal persona's registry name (config/telegram_bots.json) — same name
# api/routes/journal_ingest.py resolves via settings.resolve_persona().
_JOURNAL_PERSONA_ID = "journal"


def _journal_enabled() -> bool:
    """Whether this install actually generates files under `Personal/Journal/`.

    Two independent pipelines can produce them, and neither implies the
    other is configured, so either is sufficient to keep the reservation:

    - The journal persona's Telegram bot (settings.telegram_bots only
      includes a registry entry whose token env var is actually set — see
      config/settings.py's Settings.telegram_bots / _load_registry_bots).
    - gsheet_sync.py's own `journal_notes` output, enabled directly in
      config/gsheet_sync.yaml with no dependency on the Telegram bot at all
      (see api.services.gsheet_sync.journal_notes_configured).

    A fresh clone with neither configured has no generated file for this
    reservation to protect, so the reservation doesn't apply there.

    The Telegram check matches on `bot.name == "journal"` rather than
    resolving personas more indirectly — this is intentional, not a gap
    (Codex review of #769 asked about a bot bound to the journal persona
    under a different registry name): `"journal"` is a fixed, hardcoded
    identifier this exact string is compared against everywhere the journal
    persona is used — `journal_capture.JOURNAL_PERSONA_ID`,
    `journal_ingest._JOURNAL_PERSONA_ID`, and `resolve_persona()` itself
    (`config/settings.py`, `for bot in self.telegram_bots: if bot.name ==
    persona_id`). Renaming that registry entry away from `"journal"` doesn't
    make some *other* bot "the journal persona" under this check specifically
    — it breaks every one of those call sites identically, i.e. the entire
    capture pipeline stops working system-wide, not just this reservation.
    """
    return (
        any(bot.name == _JOURNAL_PERSONA_ID for bot in settings.telegram_bots)
        or journal_notes_configured()
    )


class VaultWriteRequest(BaseModel):
    path: str = Field(
        ...,
        min_length=1,
        description=(
            "Vault-relative path (e.g., `Inbox/news monitoring prompt.md`). "
            "Must not start with `/` or contain `..`. Parent directories are "
            "created on demand."
        ),
    )
    content: str = Field(
        ...,
        description="UTF-8 text to write. Markdown is conventional; any text is allowed.",
    )
    mode: Literal["create", "overwrite", "append"] = Field(
        default="create",
        description=(
            "`create` (default) fails if the file exists. `overwrite` replaces. "
            "`append` adds to the end (creates the file if missing)."
        ),
    )


class VaultWriteResponse(BaseModel):
    path: str
    abs_path: str
    bytes_written: int
    mode: str
    created: bool


@router.post("/write", response_model=VaultWriteResponse)
async def vault_write(request: VaultWriteRequest) -> VaultWriteResponse:
    rel = request.path.strip()
    if rel.startswith("/") or rel.startswith("~"):
        raise HTTPException(400, "path must be vault-relative (no leading / or ~)")
    rel_parts = Path(rel).parts
    if ".." in rel_parts:
        raise HTTPException(400, "path must not contain `..`")
    if rel_parts[: len(_RESERVED_PREFIX)] == _RESERVED_PREFIX and _journal_enabled():
        raise HTTPException(
            400,
            "path must not target Personal/Journal/ (reserved for the generated "
            "daily journal; capture free-form notes under Personal/Log/ instead)",
        )

    vault_root = settings.vault_path.resolve()
    target = (vault_root / rel).resolve()
    try:
        target.relative_to(vault_root)
    except ValueError:
        raise HTTPException(400, "path resolves outside the vault root")

    existed = target.exists()
    if request.mode == "create" and existed:
        raise HTTPException(
            409,
            f"file already exists at {rel}; use mode=overwrite or mode=append",
        )

    target.parent.mkdir(parents=True, exist_ok=True)

    try:
        if request.mode == "append":
            with target.open("a", encoding="utf-8") as f:
                bytes_written = f.write(request.content)
        else:
            target.write_text(request.content, encoding="utf-8")
            bytes_written = len(request.content.encode("utf-8"))
    except OSError as e:
        logger.exception("vault write failed for %s", rel)
        raise HTTPException(500, f"write failed: {e}")

    logger.info("vault write: %s (%d bytes, mode=%s)", rel, bytes_written, request.mode)
    return VaultWriteResponse(
        path=rel,
        abs_path=str(target),
        bytes_written=bytes_written,
        mode=request.mode,
        created=not existed,
    )
